//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registrodepersonal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltrabajadores
    {
        public int IDEmpresarial { get; set; }
        public string Nombres { get; set; }
        public string Apellidsos { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<System.DateTime> Fechadeingraso { get; set; }
        public string Sexo { get; set; }
        public string Area { get; set; }
    }
}
